/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 1 "CommandLine.g"

#include <stdio.h>
#include "nodes.h"
#include "mystring.h"

typedef struct My_ParseNode {
    int type;
    string_t *strvalue;
} My_ParseNode;

#define D_ParseNode_User My_ParseNode


#line 21 "CommandLine.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_gram = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 16 "CommandLine.g"
int d_final_reduction_code_1_1_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntCommandLine;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 28 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_1_gram = {1, 1, NULL, d_final_reduction_code_1_1_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_gram = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 23 "CommandLine.g"
int d_final_reduction_code_3_4_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntCommandLineGlobal;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 34 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_4_gram = {2, 3, NULL, d_final_reduction_code_3_4_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_5_gram = {2, 4, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_6_gram = {0, 4, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_7_gram = {2, 5, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_8_gram = {2, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_9_gram = {0, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_10_gram = {2, 7, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_11_gram = {2, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_12_gram = {1, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_13_gram = {2, 9, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_14_gram = {0, 9, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 29 "CommandLine.g"
int d_final_reduction_code_10_15_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntCommandLineNonGlobal;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 49 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_15_gram = {2, 10, NULL, d_final_reduction_code_10_15_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_16_gram = {2, 11, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_17_gram = {0, 11, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_18_gram = {3, 12, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_19_gram = {2, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_20_gram = {0, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_21_gram = {2, 14, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_22_gram = {2, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_23_gram = {1, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_24_gram = {2, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_25_gram = {0, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 34 "CommandLine.g"
int d_final_reduction_code_17_26_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntCommand;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 64 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_26_gram = {2, 17, NULL, d_final_reduction_code_17_26_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_27_gram = {2, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_28_gram = {0, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 42 "CommandLine.g"
int d_final_reduction_code_19_29_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntOption;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 71 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_29_gram = {5, 19, NULL, d_final_reduction_code_19_29_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_30_gram = {1, 20, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_31_gram = {0, 20, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_32_gram = {4, 21, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_33_gram = {2, 22, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_34_gram = {0, 22, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_35_gram = {4, 23, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_36_gram = {1, 24, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_39_gram = {2, 25, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_40_gram = {0, 25, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_41_gram = {2, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_42_gram = {0, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_43_gram = {1, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_46_gram = {2, 28, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_47_gram = {0, 28, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_48_gram = {1, 29, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_49_gram = {0, 29, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_50_gram = {2, 30, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_51_gram = {0, 30, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 47 "CommandLine.g"
int d_final_reduction_code_31_52_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntName;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 94 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_52_gram = {1, 31, NULL, d_final_reduction_code_31_52_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_53_gram = {2, 32, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_54_gram = {1, 32, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 52 "CommandLine.g"
int d_final_reduction_code_33_55_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).type = ntValue;   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 101 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_55_gram = {1, 33, NULL, d_final_reduction_code_33_55_gram, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_56_gram = {2, 34, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_57_gram = {1, 34, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_58_gram = {1, 35, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_60_gram = {4, 36, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_61_gram = {2, 37, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_62_gram = {0, 37, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_63_gram = {1, 38, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 71 "CommandLine.g"
int d_final_reduction_code_38_75_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  
        (D_PN(_ps, _offset)->user).strvalue = string_append((D_PN(_ps, _offset)->user).strvalue, (*(D_PN(_children[0], _offset))).start_loc.s, (*(D_PN(_children[0], _offset))).end);
        (D_PN(_ps, _offset)->user).type = ntQvalue; 
      (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 116 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_75_gram = {1, 38, NULL, d_final_reduction_code_38_75_gram, 0, 0, 0, 0, -1, 0, NULL};
#line 57 "CommandLine.g"
int d_final_reduction_code_39_76_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).strvalue = string_new();   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 121 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_76_gram = {0, 39, NULL, d_final_reduction_code_39_76_gram, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_77_gram = {4, 40, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_78_gram = {2, 41, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_79_gram = {0, 41, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_80_gram = {1, 42, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_90_gram = {2, 42, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
#line 94 "CommandLine.g"
int d_final_reduction_code_42_92_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) { 
        (D_PN(_ps, _offset)->user).strvalue = string_append((D_PN(_ps, _offset)->user).strvalue, (*(D_PN(_children[0], _offset))).start_loc.s, (*(D_PN(_children[0], _offset))).end);
        (D_PN(_ps, _offset)->user).type = ntSqvalue;
      (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 134 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_92_gram = {1, 42, NULL, d_final_reduction_code_42_92_gram, 0, 0, 0, 0, -1, 0, NULL};
#line 80 "CommandLine.g"
int d_final_reduction_code_43_93_gram(void *_ps, void **_children, int _n_children, int _offset, D_Parser *_parser) {  (D_PN(_ps, _offset)->user).strvalue = string_new();   (void)_children; (void)_n_children;  (void)_parser; return 0;}

#line 139 "CommandLine.g.d_parser.c"
D_Reduction d_reduction_93_gram = {0, 43, NULL, d_final_reduction_code_43_93_gram, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_94_gram = {1, 44, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_95_gram = {1, 45, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_96_gram = {1, 46, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_97_gram = {1, 47, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_98_gram = {1, 48, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_99_gram = {1, 49, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_100_gram = {1, 50, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_101_gram = {1, 51, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_102_gram = {1, 52, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_103_gram = {1, 53, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_104_gram = {1, 54, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_105_gram = {1, 55, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_106_gram = {1, 56, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_gram = {57, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_gram = {58, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_gram = {59, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_gram = {60, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_gram = {61, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_gram = {62, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_gram = {63, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_gram = {64, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_gram = {65, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_gram = {66, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_gram = {67, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_gram = {68, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_gram = {69, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_8_0_gram[] = {0};
D_Shift ** d_accepts_diff_8_gram[] = {
d_accepts_diff_8_0_gram
};

unsigned char d_scanner_8_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_8_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_8_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_8_0_2_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_8_1_gram[] = {&d_shift_12_gram,NULL};

unsigned char d_scanner_8_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_8_2_gram[] = {&d_shift_0_gram,NULL};

D_Shift * d_accepts_diff_9_0_gram[] = {0};
D_Shift ** d_accepts_diff_9_gram[] = {
d_accepts_diff_9_0_gram
};

unsigned char d_scanner_9_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_12_0_gram[] = {0};
D_Shift ** d_accepts_diff_12_gram[] = {
d_accepts_diff_12_0_gram
};

unsigned char d_scanner_12_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_12_2_gram[] = {&d_shift_7_gram,NULL};

D_Shift * d_accepts_diff_18_0_gram[] = {0};
D_Shift ** d_accepts_diff_18_gram[] = {
d_accepts_diff_18_0_gram
};

unsigned char d_scanner_18_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_26_0_gram[] = {0};
D_Shift ** d_accepts_diff_26_gram[] = {
d_accepts_diff_26_0_gram
};

unsigned char d_scanner_26_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_40_0_gram[] = {0};
D_Shift ** d_accepts_diff_40_gram[] = {
d_accepts_diff_40_0_gram
};

unsigned char d_scanner_40_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_40_1_gram[] = {&d_shift_6_gram,NULL};

D_Shift * d_accepts_diff_47_0_gram[] = {0};
D_Shift * d_accepts_diff_47_1_gram[] = {&d_shift_2_gram,0};
D_Shift * d_accepts_diff_47_2_gram[] = {&d_shift_0_gram,0};
D_Shift ** d_accepts_diff_47_gram[] = {
d_accepts_diff_47_0_gram,
d_accepts_diff_47_1_gram,
d_accepts_diff_47_2_gram
};

unsigned char d_scanner_47_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 
};

unsigned char d_scanner_47_0_1_gram[SCANNER_BLOCK_SIZE] = {
6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 5, 
6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_47_2_gram[] = {&d_shift_11_gram,NULL};

D_Shift * d_shift_47_3_gram[] = {&d_shift_10_gram,NULL};

unsigned char d_scanner_47_4_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 
};

unsigned char d_accepts_diff_47_4_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_accepts_diff_47_4_1_gram[SCANNER_BLOCK_SIZE] = {
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_47_4_gram[] = {&d_shift_0_gram,&d_shift_2_gram,NULL};

unsigned char d_scanner_47_5_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
};

unsigned char d_scanner_47_5_1_gram[SCANNER_BLOCK_SIZE] = {
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_47_5_gram[] = {&d_shift_2_gram,NULL};

unsigned char d_scanner_47_6_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_47_6_1_gram[SCANNER_BLOCK_SIZE] = {
0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 7, 
0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_53_0_gram[] = {0};
D_Shift * d_accepts_diff_53_1_gram[] = {&d_shift_0_gram,0};
D_Shift * d_accepts_diff_53_2_gram[] = {&d_shift_2_gram,0};
D_Shift ** d_accepts_diff_53_gram[] = {
d_accepts_diff_53_0_gram,
d_accepts_diff_53_1_gram,
d_accepts_diff_53_2_gram
};

unsigned char d_scanner_53_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 
};

unsigned char d_scanner_53_0_1_gram[SCANNER_BLOCK_SIZE] = {
3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 2, 
3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_53_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 
};

unsigned char d_accepts_diff_53_1_1_gram[SCANNER_BLOCK_SIZE] = {
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_53_1_gram[] = {&d_shift_0_gram,&d_shift_2_gram,NULL};

unsigned char d_scanner_53_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
};

unsigned char d_scanner_53_2_1_gram[SCANNER_BLOCK_SIZE] = {
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_53_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_53_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_67_0_gram[] = {0};
D_Shift ** d_accepts_diff_67_gram[] = {
d_accepts_diff_67_0_gram
};

unsigned char d_scanner_67_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_67_2_gram[] = {&d_shift_8_gram,NULL};

D_Shift * d_accepts_diff_68_0_gram[] = {0};
D_Shift * d_accepts_diff_68_1_gram[] = {&d_shift_9_gram,0};
D_Shift * d_accepts_diff_68_2_gram[] = {&d_shift_0_gram,0};
D_Shift * d_accepts_diff_68_3_gram[] = {&d_shift_2_gram,&d_shift_3_gram,&d_shift_4_gram,&d_shift_5_gram,0};
D_Shift * d_accepts_diff_68_4_gram[] = {&d_shift_6_gram,0};
D_Shift ** d_accepts_diff_68_gram[] = {
d_accepts_diff_68_0_gram,
d_accepts_diff_68_1_gram,
d_accepts_diff_68_2_gram,
d_accepts_diff_68_3_gram,
d_accepts_diff_68_4_gram
};

unsigned char d_scanner_68_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5, 6, 0, 7, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 10, 9, 9, 
};

unsigned char d_accepts_diff_68_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
};

unsigned char d_scanner_68_0_1_gram[SCANNER_BLOCK_SIZE] = {
9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 8, 
9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
8, 8, 8, 8, 8, 8, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_68_0_1_gram[SCANNER_BLOCK_SIZE] = {
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_68_0_gram[] = {&d_shift_9_gram,NULL};

D_Shift * d_shift_68_6_gram[] = {&d_shift_1_gram,NULL};

unsigned char d_scanner_68_7_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_accepts_diff_68_7_1_gram[SCANNER_BLOCK_SIZE] = {
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_68_7_gram[] = {&d_shift_0_gram,&d_shift_2_gram,&d_shift_3_gram,&d_shift_4_gram,&d_shift_5_gram,NULL};

unsigned char d_scanner_68_8_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
};

unsigned char d_scanner_68_8_1_gram[SCANNER_BLOCK_SIZE] = {
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_68_8_gram[] = {&d_shift_2_gram,&d_shift_3_gram,&d_shift_4_gram,&d_shift_5_gram,NULL};

unsigned char d_accepts_diff_68_9_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
};

unsigned char d_accepts_diff_68_9_1_gram[SCANNER_BLOCK_SIZE] = {
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_68_9_gram[] = {&d_shift_6_gram,&d_shift_2_gram,&d_shift_3_gram,&d_shift_4_gram,&d_shift_5_gram,NULL};

unsigned char d_scanner_68_10_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_68_10_1_gram[SCANNER_BLOCK_SIZE] = {
0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 11, 
0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_89_0_gram[] = {0};
D_Shift ** d_accepts_diff_89_gram[] = {
d_accepts_diff_89_0_gram
};

unsigned char d_scanner_89_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

SB_uint8 d_scanner_8_gram[3] = {
{NULL, {d_scanner_8_0_0_gram, d_scanner_8_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_2_gram, {d_scanner_8_2_0_gram, d_scanner_8_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_8_gram[3] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_9_gram[2] = {
{NULL, {d_scanner_9_0_0_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_9_gram[2] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_12_gram[3] = {
{NULL, {d_scanner_12_0_0_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_12_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_12_gram[3] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_18_gram[2] = {
{NULL, {d_scanner_18_0_0_gram, d_scanner_18_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_2_gram, {d_scanner_18_0_0_gram, d_scanner_18_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_18_gram[2] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_26_gram[2] = {
{NULL, {d_scanner_26_0_0_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_12_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_26_gram[2] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_40_gram[2] = {
{NULL, {d_scanner_40_0_0_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_40_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_40_gram[2] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_47_gram[7] = {
{NULL, {d_scanner_47_0_0_gram, d_scanner_47_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_3_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_4_gram, {d_scanner_47_4_0_gram, d_scanner_47_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_5_gram, {d_scanner_47_5_0_gram, d_scanner_47_5_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_2_gram, {d_scanner_47_6_0_gram, d_scanner_47_6_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_47_gram[7] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_47_4_0_gram, d_accepts_diff_47_4_1_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_53_gram[4] = {
{NULL, {d_scanner_53_0_0_gram, d_scanner_53_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_53_1_gram, {d_scanner_53_0_0_gram, d_scanner_53_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_5_gram, {d_scanner_53_2_0_gram, d_scanner_53_2_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_2_gram, {d_scanner_53_3_0_gram, d_scanner_53_3_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_53_gram[4] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_53_1_0_gram, d_accepts_diff_53_1_1_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_67_gram[3] = {
{NULL, {d_scanner_67_0_0_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_67_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_67_gram[3] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_68_gram[11] = {
{d_shift_68_0_gram, {d_scanner_68_0_0_gram, d_scanner_68_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_1_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_3_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_67_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_12_2_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_68_6_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_68_7_gram, {d_scanner_68_7_0_gram, d_scanner_68_0_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_68_8_gram, {d_scanner_68_8_0_gram, d_scanner_68_8_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_68_9_gram, {d_scanner_68_8_0_gram, d_scanner_68_8_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_8_2_gram, {d_scanner_68_10_0_gram, d_scanner_68_10_1_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_68_gram[11] = {
{{d_accepts_diff_68_0_0_gram, d_accepts_diff_68_0_1_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_47_4_0_gram, d_accepts_diff_68_7_1_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_68_9_0_gram, d_accepts_diff_68_9_1_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

SB_uint8 d_scanner_89_gram[2] = {
{NULL, {d_scanner_89_0_0_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}},
{d_shift_47_3_gram, {d_scanner_8_0_2_gram, d_scanner_8_0_2_gram
 , d_scanner_8_0_2_gram, d_scanner_8_0_2_gram}}
};

SB_trans_uint8 d_transition_89_gram[2] = {
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}},
{{d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram
 , d_accepts_diff_8_0_0_gram, d_accepts_diff_8_0_0_gram}}
};

unsigned char d_goto_valid_0_gram[] = {
0x2e,0x16,0x1,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_0_gram[] = {&d_reduction_14_gram,&d_reduction_25_gram};
D_RightEpsilonHint d_right_epsilon_hints_0_gram[] = {{0, 1, &d_reduction_0_gram},{0, 2, &d_reduction_1_gram},{0, 3, &d_reduction_2_gram},{1, 9, &d_reduction_4_gram},{1, 10, &d_reduction_7_gram}};
D_Reduction * d_reductions_2_gram[] = {&d_reduction_1_gram};
D_Reduction * d_reductions_3_gram[] = {&d_reduction_2_gram};
unsigned char d_goto_valid_4_gram[] = {
0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_4_gram[] = {&d_reduction_6_gram};
D_RightEpsilonHint d_right_epsilon_hints_4_gram[] = {{0, 9, &d_reduction_4_gram}};
unsigned char d_goto_valid_5_gram[] = {
0x40,0x0,0x8,0x40,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_5_gram[] = {&d_reduction_9_gram,&d_reduction_51_gram};
D_RightEpsilonHint d_right_epsilon_hints_5_gram[] = {{0, 10, &d_reduction_7_gram}};
D_Reduction * d_reductions_6_gram[] = {&d_reduction_2_gram};
unsigned char d_goto_valid_7_gram[] = {
0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_7_gram[] = {&d_reduction_17_gram};
D_RightEpsilonHint d_right_epsilon_hints_7_gram[] = {{0, 13, &d_reduction_15_gram}};
unsigned char d_goto_valid_8_gram[] = {
0x0,0x0,0x2,0x80,0x1,0x10,0x0,0x3,0x20};
unsigned char d_goto_valid_9_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x20};
D_Reduction * d_reductions_9_gram[] = {&d_reduction_4_gram};
unsigned char d_goto_valid_10_gram[] = {
0x80,0x1,0x0,0x0,0x0,0x0,0x0,0x1,0x20};
D_Reduction * d_reductions_10_gram[] = {&d_reduction_7_gram};
D_Reduction * d_reductions_11_gram[] = {&d_reduction_13_gram};
unsigned char d_goto_valid_12_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x1,0x21};
unsigned char d_goto_valid_13_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x20};
D_Reduction * d_reductions_13_gram[] = {&d_reduction_15_gram};
D_Reduction * d_reductions_14_gram[] = {&d_reduction_94_gram};
D_Reduction * d_reductions_15_gram[] = {&d_reduction_106_gram};
unsigned char d_goto_valid_16_gram[] = {
0x0,0x20,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_16_gram[] = {&d_reduction_20_gram};
D_RightEpsilonHint d_right_epsilon_hints_16_gram[] = {{0, 29, &d_reduction_18_gram}};
unsigned char d_goto_valid_17_gram[] = {
0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_17_gram[] = {&d_reduction_28_gram};
D_RightEpsilonHint d_right_epsilon_hints_17_gram[] = {{0, 30, &d_reduction_26_gram}};
unsigned char d_goto_valid_18_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x10,0x0,0x2,0x0};
D_Reduction * d_reductions_18_gram[] = {&d_reduction_52_gram};
D_Reduction * d_reductions_19_gram[] = {&d_reduction_54_gram};
D_Reduction * d_reductions_20_gram[] = {&d_reduction_24_gram};
D_Reduction * d_reductions_21_gram[] = {&d_reduction_5_gram};
D_Reduction * d_reductions_22_gram[] = {&d_reduction_8_gram};
unsigned char d_goto_valid_23_gram[] = {
0x0,0x0,0x2,0x80,0x1,0x10,0x0,0x3,0x20};
D_Reduction * d_reductions_24_gram[] = {&d_reduction_12_gram};
D_Reduction * d_reductions_25_gram[] = {&d_reduction_101_gram};
unsigned char d_goto_valid_26_gram[] = {
0x0,0x0,0x0,0x20,0x0,0x0,0x8,0x0,0x1};
D_Reduction * d_reductions_26_gram[] = {&d_reduction_49_gram};
D_Reduction * d_reductions_27_gram[] = {&d_reduction_50_gram};
D_Reduction * d_reductions_28_gram[] = {&d_reduction_16_gram};
unsigned char d_goto_valid_29_gram[] = {
0x0,0xc0,0x0,0x0,0x0,0x0,0x0,0x1,0x20};
D_Reduction * d_reductions_29_gram[] = {&d_reduction_18_gram};
unsigned char d_goto_valid_30_gram[] = {
0x0,0x0,0x8,0x40,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_30_gram[] = {&d_reduction_26_gram,&d_reduction_51_gram};
D_Reduction * d_reductions_31_gram[] = {&d_reduction_53_gram};
D_Reduction * d_reductions_32_gram[] = {&d_reduction_10_gram};
D_Reduction * d_reductions_33_gram[] = {&d_reduction_11_gram};
unsigned char d_goto_valid_34_gram[] = {
0x0,0x0,0x0,0x80,0x1,0x10,0x0,0x2,0x0};
D_Reduction * d_reductions_35_gram[] = {&d_reduction_48_gram};
D_Reduction * d_reductions_36_gram[] = {&d_reduction_19_gram};
unsigned char d_goto_valid_37_gram[] = {
0x0,0x0,0x2,0x80,0x1,0x10,0x0,0x3,0x20};
D_Reduction * d_reductions_38_gram[] = {&d_reduction_23_gram};
D_Reduction * d_reductions_39_gram[] = {&d_reduction_27_gram};
unsigned char d_goto_valid_40_gram[] = {
0x0,0x0,0x30,0x0,0x0,0x0,0x4,0x80,0x0};
D_Reduction * d_reductions_40_gram[] = {&d_reduction_31_gram};
D_RightEpsilonHint d_right_epsilon_hints_40_gram[] = {{0, 44, &d_reduction_29_gram}};
D_Reduction * d_reductions_41_gram[] = {&d_reduction_21_gram};
D_Reduction * d_reductions_42_gram[] = {&d_reduction_22_gram};
D_Reduction * d_reductions_43_gram[] = {&d_reduction_100_gram};
D_Reduction * d_reductions_44_gram[] = {&d_reduction_29_gram};
D_Reduction * d_reductions_45_gram[] = {&d_reduction_30_gram};
unsigned char d_goto_valid_46_gram[] = {
0x0,0x0,0x0,0x10,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_46_gram[] = {&d_reduction_47_gram};
unsigned char d_goto_valid_47_gram[] = {
0x0,0x0,0x0,0x8,0x1e,0x51,0xc0,0xb,0x38};
D_Reduction * d_reductions_48_gram[] = {&d_reduction_96_gram};
D_Reduction * d_reductions_49_gram[] = {&d_reduction_104_gram};
D_Reduction * d_reductions_50_gram[] = {&d_reduction_105_gram};
unsigned char d_goto_valid_51_gram[] = {
0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_51_gram[] = {&d_reduction_34_gram};
D_RightEpsilonHint d_right_epsilon_hints_51_gram[] = {{0, 62, &d_reduction_32_gram}};
D_Reduction * d_reductions_52_gram[] = {&d_reduction_43_gram};
unsigned char d_goto_valid_53_gram[] = {
0x0,0x0,0x0,0x0,0x8,0x50,0x0,0xa,0x0};
D_Reduction * d_reductions_53_gram[] = {&d_reduction_55_gram};
D_Reduction * d_reductions_54_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_55_gram[] = {&d_reduction_43_gram};
D_Reduction * d_reductions_56_gram[] = {&d_reduction_43_gram};
D_Reduction * d_reductions_57_gram[] = {&d_reduction_58_gram};
D_Reduction * d_reductions_58_gram[] = {&d_reduction_58_gram};
unsigned char d_goto_valid_59_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0};
D_Reduction * d_reductions_59_gram[] = {&d_reduction_93_gram};
unsigned char d_goto_valid_60_gram[] = {
0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_60_gram[] = {&d_reduction_76_gram};
D_Reduction * d_reductions_61_gram[] = {&d_reduction_46_gram};
unsigned char d_goto_valid_62_gram[] = {
0x0,0x0,0x80,0x4,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_62_gram[] = {&d_reduction_32_gram,&d_reduction_42_gram};
D_Reduction * d_reductions_63_gram[] = {&d_reduction_56_gram};
unsigned char d_goto_valid_64_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0};
D_Reduction * d_reductions_64_gram[] = {&d_reduction_79_gram};
unsigned char d_goto_valid_65_gram[] = {
0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_65_gram[] = {&d_reduction_62_gram};
D_Reduction * d_reductions_66_gram[] = {&d_reduction_33_gram};
unsigned char d_goto_valid_67_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x1,0x22};
unsigned char d_goto_valid_68_gram[] = {
0x0,0x0,0x0,0x0,0x0,0xf4,0xff,0xff,0x3f};
unsigned char d_goto_valid_69_gram[] = {
0x0,0x0,0x0,0x0,0x40,0xf0,0xff,0xff,0x3f};
D_Reduction * d_reductions_70_gram[] = {&d_reduction_102_gram};
unsigned char d_goto_valid_71_gram[] = {
0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_71_gram[] = {&d_reduction_40_gram};
D_Reduction * d_reductions_72_gram[] = {&d_reduction_41_gram};
D_Reduction * d_reductions_73_gram[] = {&d_reduction_95_gram};
D_Reduction * d_reductions_74_gram[] = {&d_reduction_97_gram};
D_Reduction * d_reductions_75_gram[] = {&d_reduction_98_gram};
D_Reduction * d_reductions_76_gram[] = {&d_reduction_99_gram};
D_Reduction * d_reductions_77_gram[] = {&d_reduction_103_gram};
D_Reduction * d_reductions_78_gram[] = {&d_reduction_78_gram};
D_Reduction * d_reductions_79_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_80_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_81_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_82_gram[] = {&d_reduction_92_gram};
D_Reduction * d_reductions_83_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_84_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_85_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_86_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_87_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_88_gram[] = {&d_reduction_80_gram};
unsigned char d_goto_valid_89_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x8};
D_Reduction * d_reductions_89_gram[] = {&d_reduction_77_gram};
D_Reduction * d_reductions_90_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_91_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_92_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_93_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_94_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_95_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_96_gram[] = {&d_reduction_75_gram};
D_Reduction * d_reductions_97_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_98_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_99_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_100_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_101_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_102_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_103_gram[] = {&d_reduction_63_gram};
D_Reduction * d_reductions_104_gram[] = {&d_reduction_60_gram,&d_reduction_63_gram};
D_Reduction * d_reductions_105_gram[] = {&d_reduction_63_gram};
unsigned char d_goto_valid_106_gram[] = {
0x0,0x0,0x0,0x1,0x1e,0x51,0xc0,0xb,0x38};
D_Reduction * d_reductions_107_gram[] = {&d_reduction_90_gram};
D_Reduction * d_reductions_108_gram[] = {&d_reduction_35_gram};
D_Reduction * d_reductions_109_gram[] = {&d_reduction_36_gram};
D_Reduction * d_reductions_110_gram[] = {&d_reduction_36_gram};
D_Reduction * d_reductions_111_gram[] = {&d_reduction_36_gram};
D_Reduction * d_reductions_112_gram[] = {&d_reduction_39_gram};
unsigned short d_gotos_gram[241] = {
2,3,4,10,5,11,14,17,6,7,22,8,23,24,27,9,
30,29,12,28,31,18,19,16,32,33,48,26,35,13,16,63,
16,40,20,65,66,15,69,18,19,37,38,70,13,107,21,15,
45,46,36,64,20,41,19,42,0,0,0,16,58,25,59,26,
34,15,20,108,67,18,19,68,72,15,16,49,73,16,47,15,
50,0,20,39,0,71,0,0,0,16,0,44,52,0,43,15,
16,0,53,54,55,56,0,0,0,57,0,16,0,58,0,59,
0,0,0,0,0,0,0,60,61,62,15,0,49,0,0,0,
0,0,0,0,50,51,16,79,0,80,81,82,83,84,85,86,
87,88,89,90,91,92,15,74,49,75,76,77,44,26,71,78,
50,51,16,93,0,0,0,0,0,94,95,96,97,98,99,100,
101,102,103,104,105,106,15,74,49,75,76,77,44,26,71,78,
50,51,16,109,0,0,0,0,0,0,0,0,110,54,55,111,
0,0,0,112,0,0,0,58,0,59,0,0,0,0,0,0,
0,60,61,113,15,0,49,0,0,0,0,0,0,0,50,51,
16};


D_State d_states_gram[] = {
{d_goto_valid_0_gram, 1, {2, d_reductions_0_gram}, {5, d_right_epsilon_hints_0_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_3_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_4_gram, 1, {1, d_reductions_4_gram}, {1, d_right_epsilon_hints_4_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_5_gram, 1, {2, d_reductions_5_gram}, {1, d_right_epsilon_hints_5_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_6_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_7_gram, 5, {1, d_reductions_7_gram}, {1, d_right_epsilon_hints_7_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_8_gram, 10, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_8_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_8_gram, d_accepts_diff_8_gram, -1},
{d_goto_valid_9_gram, 46, {1, d_reductions_9_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_9_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_9_gram, d_accepts_diff_9_gram, -1},
{d_goto_valid_10_gram, -5, {1, d_reductions_10_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_9_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_9_gram, d_accepts_diff_9_gram, -1},
{NULL, -2147483647, {1, d_reductions_11_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_12_gram, 37, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_12_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_12_gram, d_accepts_diff_12_gram, -1},
{d_goto_valid_13_gram, 39, {1, d_reductions_13_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_9_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_9_gram, d_accepts_diff_9_gram, -1},
{NULL, -2147483647, {1, d_reductions_14_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_15_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_16_gram, -3, {1, d_reductions_16_gram}, {1, d_right_epsilon_hints_16_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_17_gram, -2, {1, d_reductions_17_gram}, {1, d_right_epsilon_hints_17_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_18_gram, 20, {1, d_reductions_18_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_18_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_18_gram, d_accepts_diff_18_gram, -1},
{NULL, -2147483647, {1, d_reductions_19_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_20_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_21_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_22_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_23_gram, -8, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_8_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_8_gram, d_accepts_diff_8_gram, -1},
{NULL, -2147483647, {1, d_reductions_24_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_25_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_26_gram, 1, {1, d_reductions_26_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_26_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_26_gram, d_accepts_diff_26_gram, -1},
{NULL, -2147483647, {1, d_reductions_27_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_28_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_29_gram, -27, {1, d_reductions_29_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_9_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_9_gram, d_accepts_diff_9_gram, -1},
{d_goto_valid_30_gram, -14, {2, d_reductions_30_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_31_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_32_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_33_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_34_gram, -22, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_18_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_18_gram, d_accepts_diff_18_gram, -1},
{NULL, -2147483647, {1, d_reductions_35_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_36_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_37_gram, -38, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_8_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_8_gram, d_accepts_diff_8_gram, -1},
{NULL, -2147483647, {1, d_reductions_38_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_39_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_40_gram, -28, {1, d_reductions_40_gram}, {1, d_right_epsilon_hints_40_gram}, {0, NULL}, 1, NULL, (void*)d_scanner_40_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_40_gram, d_accepts_diff_40_gram, -1},
{NULL, -2147483647, {1, d_reductions_41_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_42_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_43_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_44_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_45_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_46_gram, 2, {1, d_reductions_46_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_47_gram, -65, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_47_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_47_gram, d_accepts_diff_47_gram, -1},
{NULL, -2147483647, {1, d_reductions_48_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_49_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_50_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_51_gram, -9, {1, d_reductions_51_gram}, {1, d_right_epsilon_hints_51_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_52_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_53_gram, -16, {1, d_reductions_53_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_53_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_53_gram, d_accepts_diff_53_gram, -1},
{NULL, -2147483647, {1, d_reductions_54_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_55_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_56_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_57_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_58_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_59_gram, 8, {1, d_reductions_59_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_60_gram, 3, {1, d_reductions_60_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_61_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_62_gram, -45, {2, d_reductions_62_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_63_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_64_gram, 3, {1, d_reductions_64_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_65_gram, -6, {1, d_reductions_65_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_66_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_67_gram, -20, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_67_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_67_gram, d_accepts_diff_67_gram, -1},
{d_goto_valid_68_gram, -93, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_68_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_68_gram, d_accepts_diff_68_gram, -1},
{d_goto_valid_69_gram, -125, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_68_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_68_gram, d_accepts_diff_68_gram, -1},
{NULL, -2147483647, {1, d_reductions_70_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_71_gram, -20, {1, d_reductions_71_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_72_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_73_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_74_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_75_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_76_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_77_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_78_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_79_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_80_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_81_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_82_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_83_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_84_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_85_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_86_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_87_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_88_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_89_gram, -13, {1, d_reductions_89_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_89_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_89_gram, d_accepts_diff_89_gram, -1},
{NULL, -2147483647, {1, d_reductions_90_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_91_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_92_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_93_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_94_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_95_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_96_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_97_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_98_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_99_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_100_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_101_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_102_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_103_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {2, d_reductions_104_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_105_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_106_gram, -171, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_47_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_47_gram, d_accepts_diff_47_gram, -1},
{NULL, -2147483647, {1, d_reductions_107_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_108_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_109_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_110_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_111_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_112_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_gram[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "commandline", 11, -1},
{D_SYMBOL_EBNF, "commandline__2", 14, -1},
{D_SYMBOL_NTERM, "commandlineWithGlobalOptions", 28, -1},
{D_SYMBOL_INTERNAL, "commandlineWithGlobalOptions__9", 31, -1},
{D_SYMBOL_EBNF, "commandlineWithGlobalOptions__4", 31, -1},
{D_SYMBOL_INTERNAL, "commandlineWithGlobalOptions__4__8", 34, -1},
{D_SYMBOL_EBNF, "commandlineWithGlobalOptions__4__6", 34, -1},
{D_SYMBOL_INTERNAL, "commandlineWithGlobalOptions__4__6__7", 37, -1},
{D_SYMBOL_INTERNAL, "commandlineWithGlobalOptions__4__5", 34, -1},
{D_SYMBOL_NTERM, "commandLineWithoutGlobalOptions", 31, -1},
{D_SYMBOL_INTERNAL, "commandLineWithoutGlobalOptions__16", 35, -1},
{D_SYMBOL_EBNF, "commandLineWithoutGlobalOptions__11", 35, -1},
{D_SYMBOL_INTERNAL, "commandLineWithoutGlobalOptions__11__15", 39, -1},
{D_SYMBOL_EBNF, "commandLineWithoutGlobalOptions__11__13", 39, -1},
{D_SYMBOL_INTERNAL, "commandLineWithoutGlobalOptions__11__13__14", 43, -1},
{D_SYMBOL_INTERNAL, "commandLineWithoutGlobalOptions__11__12", 39, -1},
{D_SYMBOL_NTERM, "command", 7, -1},
{D_SYMBOL_INTERNAL, "command__18", 11, -1},
{D_SYMBOL_NTERM, "option", 6, -1},
{D_SYMBOL_INTERNAL, "option__30", 10, -1},
{D_SYMBOL_EBNF, "option__22", 10, -1},
{D_SYMBOL_INTERNAL, "option__22__29", 14, -1},
{D_SYMBOL_EBNF, "option__22__25", 14, -1},
{D_SYMBOL_EBNF, "option__22__25__28", 18, -1},
{D_SYMBOL_INTERNAL, "option__22__25__27", 18, -1},
{D_SYMBOL_INTERNAL, "option__22__25__26", 18, -1},
{D_SYMBOL_EBNF, "option__22__24", 14, -1},
{D_SYMBOL_INTERNAL, "option__22__23", 14, -1},
{D_SYMBOL_INTERNAL, "option__21", 10, -1},
{D_SYMBOL_INTERNAL, "option__20", 10, -1},
{D_SYMBOL_NTERM, "name", 4, -1},
{D_SYMBOL_INTERNAL, "name__32", 8, -1},
{D_SYMBOL_NTERM, "value", 5, -1},
{D_SYMBOL_INTERNAL, "value__35", 9, -1},
{D_SYMBOL_EBNF, "value__34", 9, -1},
{D_SYMBOL_NTERM, "qvalue", 6, -1},
{D_SYMBOL_INTERNAL, "qvalue__39", 10, -1},
{D_SYMBOL_EBNF, "qvalue__38", 10, -1},
{D_SYMBOL_EBNF, " _synthetic__37", 15, -1},
{D_SYMBOL_NTERM, "sqvalue", 7, -1},
{D_SYMBOL_INTERNAL, "sqvalue__43", 11, -1},
{D_SYMBOL_EBNF, "sqvalue__42", 11, -1},
{D_SYMBOL_EBNF, " _synthetic__41", 15, -1},
{D_SYMBOL_NTERM, "NAME", 4, -1},
{D_SYMBOL_NTERM, "SLASH", 5, -1},
{D_SYMBOL_NTERM, "VALUECHARS", 10, -1},
{D_SYMBOL_NTERM, "EXTRASCII_VALUECHARS", 20, -1},
{D_SYMBOL_NTERM, "UTF_VALUECHARS", 14, -1},
{D_SYMBOL_NTERM, "ASCII_CONTROLCHARS", 18, -1},
{D_SYMBOL_NTERM, "EQUALS", 6, -1},
{D_SYMBOL_NTERM, "HYPHEN", 6, -1},
{D_SYMBOL_NTERM, "COMMA", 5, -1},
{D_SYMBOL_NTERM, "NULL", 4, -1},
{D_SYMBOL_NTERM, "SQUOTE", 6, -1},
{D_SYMBOL_NTERM, "DQUOTE", 6, -1},
{D_SYMBOL_NTERM, "WSPACE", 6, -1},
{D_SYMBOL_REGEX, "[a-zA-Z0-9_]+", 13, -1},
{D_SYMBOL_STRING, "/", 1, -1},
{D_SYMBOL_REGEX, "[\\\\u0021\\\\u0023-\\\\u0026\\\\u0028-\\\\u002b\\\\u002e\\\\u003a-\\\\u003c\\\\u003e-\\\\u0040\\\\u005b-\\\\u005e\\\\u0060\\\\u007b-\\\\u007e]+", 144, -1},
{D_SYMBOL_REGEX, "[\\\\u0080-\\\\u00ff]+", 22, -1},
{D_SYMBOL_REGEX, "[\\\\u0100-\\\\uffff]+", 22, -1},
{D_SYMBOL_REGEX, "[\\\\u0002-\\\\u001f]+", 22, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "-", 1, -1},
{D_SYMBOL_STRING, ",", 1, -1},
{D_SYMBOL_STRING, "", 0, -1},
{D_SYMBOL_STRING, "'", 1, -1},
{D_SYMBOL_STRING, "\\\"", 4, -1},
{D_SYMBOL_REGEX, "[ \\t]", 6, -1},
};

D_ParserTables parser_tables_gram = {
113, d_states_gram, d_gotos_gram, 0, 70, d_symbols_gram, NULL, 0, NULL, 0};
